custom:
  path:
    resource: file:///D:/ImageUpload example/src/main/downloads/
    upload: /upload/**

server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  
  handlerbars:
    suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example_chat_db?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: false #sql에 실행된 결과를 로그창에 표시
    properties:
      hibernate.format_sql: true 

  jackson:
    serialization:
      fail-on-empty-beans: false